# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: SEUNG CHANY
# Description of the Site
description: DEVELOPER
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/main.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: seungchanystar@gmail.com
facebook_username: seungchany
twitter_username: seungchanystar
instagram_username: seungchanystar
linkedin_username: seungchanystar
github_username:  seungchanystar
youtube_channel_id: UCgyUNy0y_eQgacI0UlKKtQw
reddit_username: seungchany
behance_username: seungchany
dribbble_username: seungchany
spotify_username: seungchany

# Google Analytics
google-analytics: G-N4QFF2Q7D6

# Disqus
disqus-shortname: seungchanystar

# Name of the Author
author-name: seungchanystar
# URL for the Image of the Author
# author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-image: /assets/images/Pofile_Photo.png
# 60 Words About the Author
author-about: 
  University
  <hr style="border:solid 0.3px black;"/>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:50%; display:flex" >
    Korea National Open University, Bachelor of Computer Science
    </div>
    <div>
    August, 2022 &nbsp; graduated &nbsp;&nbsp; Seoul, Korea
    </div>
  </div></br>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:40%; display:flex" >
    Jeonbuk National University, Bachelor of Law
    </div>
    <div>
    February, 2012 &nbsp; graduated <br/>
    <div>Jeollabuk-do Jeonju-si, Korea</div>
    </div>

  </div></br>

  PROJECTS
   <hr style="border:solid 0.3px black;"/>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:60%; display:flex;">
      <div>
      Pharmaceutical company CRM System<br/> 
      [APP] [Front-end Developer]<br/>
      Skills - React-Native, Sass, JavaScript, TypeScript, Firebase, NodeJs, Git, GitLab, Sourcetree, Android Studio, Xcode
      </div>
    </div>
    <div>
    July 2022 - November 2022<br/>
    <div style="font-weight:400;">Hanmi Healthcare, Inc <br/> Seoul, Korea </div> 
    </div>
  </div>

  <hr style="border:dashed 0.3px black;"/>

  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:60%; display:flex;">
      <div>
      Kiosk Manage<br/> 
      [Web] [Front-end Developer]<br/>
      Skills - Html, Css, Sass, JavaScript, TypeScript, React, NodeJs, Git
      </div>
    </div>
    <div>
    February 2022 - June 2022<br/>
    <div style="font-weight:400;">Hunique, Inc - Seoul, Korea </div> 
    </div>
  </div>

  <hr style="border:dashed 0.3px black;"/>

  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:50%; display:flex;">
      <div>
      Customer service center Manage<br/>
      [Web] [Full-stack Developer]<br/>
      Skills - Html, Css, Sass, JavaScript, Vue, React, NodeJs, Java, Jsp, Spring, Mysql, Oracle, Linux, Svn
      </div>
    </div>
    <div>
    September 2021 - January 2022<br/>
    <div style="font-weight:400;">It pack, Inc - Seoul, Korea </div>
    </div>
  </div>  

  <hr style="border:dashed 0.3px black;"/>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
      <div style="width:60%; display:flex;">
          <div>
          Clothing Shopping Online Mall <br/>
          [WEB, APP][Full-stack Developer] <br/>
          Skills - Html, Css, Sass, JavaScript, React-Native, NodeJs, PHP, Mysql, Git
          </div>
      </div>
      <div>
      August 2020 - July 2021<br/>
      <div style="font-weight:400;">IT Energy - Seoul, Korea </div>
      </div>
  </div>

   <hr style="border:dashed 0.3px black;"/> 
     <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
      <div style="width:60%; display:flex;">
          <div>
          GongGonggigwan cloud storage <br/>
          [WEB][Full-stack Developer] <br/>
          Skills - Html, Css, Sass, JavaScript, PHP, JAVA, Spring, MariaDB, Linux, Kubernetes
          </div>
      </div>
      <div>
      Octor 2019 - May 2020<br/>
      <div style="font-weight:400;"> IanSoft - Seoul, Korea </div>
      </div>
  </div></br>


  CERTIFICATE
  <hr style="border:solid 0.5px black;"/>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:78%; display:flex" >Jeongbocheorigisa </div> <div>June, 2022</div>
  </div></br>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:78%; display:flex" >Jeongbocgigiunyonggineungsa </div> <div>December, 2020</div>
  </div></br>

  Education
  <hr style="border:solid 0.5px black;"/>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:60%;" >
    Blockchain service development basic course<br/>
    <i>Korea Internet & Security Agency</i>
    </div>
    <div>
    August 2021<br/>
    </div>
  </div></br>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:50%; display:flex" >
    Mobile app development
    </div> 
    <div>
    September 2020 - February 2021<br/>
    </div>
  </div></br>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:60%; display:flex" >
    Arduino training course 
    </div> 
    <div>
    May 2020 - July 2020<br/>
    </div>
  </div></br>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:60%; display:flex" >
    "2020 call for code" Hackathon
    </div> 
    <div>
    May 2020 - June 2020<br/>
    </div>
  </div></br>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:60%;" >
    Fintech service development<br/>
    <i>Korea Internet & Security Agency</i>
    </div> 
    <div>
    Octor 2019<br/>
    </div>
  </div></br>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:60%;" >
    Insuretech service development<br/>
    <i>Korea Internet & Security Agency</i>
    </div> 
    <div>
    September 2019<br/>
    </div>
  </div></br>
  <div class="about-author-history-content" style="display:flex; justify-content:space-between;">
    <div style="width:60%; display:flex" >
    Hackathon Using Raspberry Pi 
    </div> 
    <div>
    November 2016 <br/>
    </div>
  </div></br>

  
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/seungchanystar

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
