# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: I AM SEUNGCHANY
# Description of the Site
description: NOW FRONT-END DEVELOPER && TO FULL-STACK
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/main.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: seungchanystar@gmail.com
facebook_username: seungchany
twitter_username: seungchanystar
instagram_username: seungchanystar
linkedin_username: seungchanystar
github_username:  seungchanystar
youtube_channel_id: UCgyUNy0y_eQgacI0UlKKtQw
reddit_username: seungchany
behance_username: seungchany
dribbble_username: seungchany
spotify_username: seungchany

# Google Analytics
google-analytics: G-N4QFF2Q7D6

# Disqus
disqus-shortname: seungchanystar

# Name of the Author
author-name: seungchanystar
# URL for the Image of the Author
# author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-image: ./assets/images/Pofile_Photo.png
# 60 Words About the Author
author-about: is going
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/seungchanystar

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
